import manimg from "../images/man.jpg";
import womanimg from "../images/woman.jpg";

const users = [
  {
    created_on: "2022-03-26T09:32:05.500266+05:30",
    maslak: "Deobandi (Tablighi)",
    biradari: null,
    full_name: "Mohammad Mustafa",
    fathers_name: "Mulka Husain Jamadar",
    mothers_name: "Naseem Begum",
    contact_number: "8983768055",
    whatsapp_country_code: "+91",
    city: "Nanded",
    whatsapp_number: "7057677066",
    contact_of: "PR",
    date_of_birth: "2000-07-24",
    age: 22,
    gender: "ML",
    height: 5.3,
    martial_status: "Umarried",
    detail_for_this_status: null,
    no_of_children: null,
    duration_after_khula_or_divorce: null,
    physical_status: "NM",
    handicap_detail: null,
    education: "GR",
    degree: "D.el.ed",
    occupation: "Full Stack Developer",
    home_address: "Sayyadan Nanded",
    no_of_brothers: 1,
    no_of_married_brothers: 1,
    no_of_sisters: 1,
    no_of_married_sisters: 1,
    fathers_occupation: "Teacher",
    mothers_occupation: "Teacher",
    hobbies: "Cricket, Video Games, Coding",
    weight: 72,
    country: "India",
    state: "Maharashtra",
    city_native:  "Nanded",
    country_current: "India",
    state_current: "Maharashtra",
    city_current:"Mumbai",
    expectations: "Kuch Nahi",
    extra_information: "Bas Ab!",
    thumbnail: manimg,
    photo_1: null,
    photo_2: null,
    photo_3: null,
    age_group: "22-25",
    slug: "mohammad-mustafa",
    profile_code: "076873",
  },
  {
    created_on: "2022-03-26T09:32:05.500266+05:30",
    maslak: "Deobandi (Tablighi)",
    biradari: null,
    full_name: "Unkown",
    fathers_name: "Nahi Maloom",
    mothers_name: "Naseem Begum",
    contact_number: "8983768055",
    whatsapp_country_code: "+91",
    city: "Nanded",
    whatsapp_number: "7057677066",
    contact_of: "PR",
    date_of_birth: "2000-07-24",
    age: 22,
    gender: "ML",
    height: 5.3,
    martial_status: "Umarried",
    detail_for_this_status: null,
    no_of_children: null,
    duration_after_khula_or_divorce: null,
    physical_status: "NM",
    handicap_detail: null,
    education: "GR",
    degree: "D.el.ed",
    occupation: "Teacher",
    home_address: "Sayyadan Nanded",
    no_of_brothers: 1,
    no_of_married_brothers: 1,
    no_of_sisters: 1,
    no_of_married_sisters: 1,
    fathers_occupation: "Teacher",
    mothers_occupation: "Teacher",
    hobbies: "Cricket, Video Games, Coding",
    weight: 72,
    country: "India",
    state: "Maharashtra",
    city_native: "Nanded",
    country_current: "India",
    state_current: "Maharashtra",
    city_current: "Mumbai",
    expectations: "Kuch Nahi",
    extra_information: "Bas Ab!",
    thumbnail: womanimg,
    photo_1: null,
    photo_2: null,
    photo_3: null,
    age_group: "22-25",
    slug: "unkown",
    profile_code: "076875",
  },
];

const userData = {
  created_on: "2022-03-26T09:32:05.500266+05:30",
  maslak: "Deobandi (Tablighi)",
  biradari: null,
  full_name: "Mohammad Mustafa",
  fathers_name: "Mulka Husain Jamadar",
  mothers_name: "Naseem Begum",
  contact_number: "8983768055",
  whatsapp_country_code: "+91",
  city: "Nanded",
  whatsapp_number: "7057677066",
  contact_of: "PR",
  date_of_birth: "2000-07-24",
  age: 22,
  gender: "ML",
  height: 5.3,
  martial_status: "UM",
  detail_for_this_status: null,
  no_of_children: null,
  duration_after_khula_or_divorce: null,
  physical_status: "NM",
  handicap_detail: null,
  education: "GR",
  degree: "D.el.ed",
  occupation: "Full Stack Developer",
  home_address: "Sayyadan Nanded",
  no_of_brothers: 1,
  no_of_married_brothers: 1,
  no_of_sisters: 1,
  no_of_married_sisters: 1,
  fathers_occupation: "Teacher",
  mothers_occupation: "Teacher",
  hobbies: "Cricket, Video Games, Coding",
  weight: 72,
  country: "India",
  state: "Maharashtra",
  city_native: "Nanded",
  country_current: "India",
  state_current: "Maharashtra",
  city_current: "Mumbai",
  expectations: "Kuch Nahi",
  extra_information: "Bas Ab!",
  thumbnail: null,
  photo_1: null,
  photo_2: null,
  photo_3: null,
  age_group: "22-25",
  slug: "mohammad-mustafa",
  profile_code: "076873",
};

export { users, userData };
