import manimg from "../images/man.jpg";

import womanimg from "../images/woman.jpg";
const location = "Nanded";
const education = "Graduate";
 const users = [
  {
    id: 1,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 2,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 3,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 4,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 5,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 6,
    name: "Unknown",
    work: `	Assisstant Teacher (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 7,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 8,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 9,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 10,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 11,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 12,
    name: "Unknown",
    work: `	Assisstant Teacher (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 13,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 14,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 15,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 16,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 17,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 18,
    name: "Unknown",
    work: `	Assisstant Teacher (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 19,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 20,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 21,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 22,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 23,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 24,
    name: "Unknown",
    work: `	Assisstant Teacher (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 25,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 26,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 27,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 28,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 29,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 30,
    name: "Unknown",
    work: `	Assisstant Teacher (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 31,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 32,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 33,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 34,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 35,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 36,
    name: "Unknown",
    work: `	Assisstant Teacher (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 37,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 38,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 39,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 40,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 41,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 42,
    name: "Unknown",
    work: `	Assisstant Teacher (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 43,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 44,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 45,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 46,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 47,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 48,
    name: "Unknown",
    work: `	Assisstant Teacher (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 49,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 50,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 51,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 52,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 53,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 54,
    name: "Unknown",
    work: `	Assisstant Teacher (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 55,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 56,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 57,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },

  {
    id: 58,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 59,
    name: "Unknown",
    work: `	Assisstant Teacher (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 60,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 61,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 62,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 63,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 64,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 65,
    name: "Unknown",
    work: `	Assisstant Teacher (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 66,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 67,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 68,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 69,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 70,
    name: "Mohammad Mustafa",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: manimg,
  },
  {
    id: 71,
    name: "Unknown",
    work: `	Assisstant Teacher (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
  {
    id: 72,
    name: "Unknown",
    work: `Full Stack Developer (${education})`,
    gender: "Male",
    maslak: "Tablighi",
    age: `22 Years (${location})`,
    img: womanimg,
  },
];

const userData = {
  created_on: "2022-03-26T09:32:05.500266+05:30",
  maslak: "Deobandi (Tablighi)",
  biradari: null,
  full_name: "Mohammad Mustafa",
  fathers_name: "Mulka Husain Jamadar",
  mothers_name: "Naseem Begum",
  contact_number: "8983768055",
  whatsapp_country_code: "+91",
  city: "Nanded",
  whatsapp_number: "7057677066",
  contact_of: "PR",
  date_of_birth: "2000-07-24",
  age: 22,
  gender: "ML",
  height: 5.3,
  martial_status: "UM",
  detail_for_this_status: null,
  no_of_children: null,
  duration_after_khula_or_divorce: null,
  physical_status: "NM",
  handicap_detail: null,
  education: "GR",
  degree: "D.el.ed",
  occupation: "Full Stack Developer",
  home_address: "Sayyadan Nanded",
  no_of_brothers: 1,
  no_of_married_brothers: 1,
  no_of_sisters: 1,
  no_of_married_sisters: 1,
  fathers_occupation: "Teacher",
  mothers_occupation: "Teacher",
  hobbies: "Cricket, Video Games, Coding",
  weight: 72,
  country: "India",
  state: "Maharashtra",
  city_native: "Nanded",
  country_current: "India",
  state_current: "Maharashtra",
  city_current: "Mumbai",
  expectations: "Kuch Nahi",
  extra_information: "Bas Ab!",
  thumbnail: null,
  photo_1: null,
  photo_2: null,
  photo_3: null,
  age_group: "22-25",
  slug: "mohammad-mustafa",
  profile_code: "076873",
};

export { users, userData}