const selectGenderList = [
  {
    value: "Male",
    label: "Male",
  },
  {
    value: "Female",
    label: "Female",
  },
];

const forMaritalStatus = [
  { value: "Unmarried", label: "Unmarried", id: 1 },
  { value: "Divorced", label: "Divorced", id: 2 },
  { value: "Awaiting Divorce", label: "Awaiting Divorce", id: 3 },
  { value: "Khula", label: "Khula", id: 4 },
  { value: "2nd marriage", label: "2nd marriage", id: 5 },
  { value: "Widow (Female)", label: "Widow (Female)", id: 6 },
  { value: "Widower (Male)", label: "Widower (Male)", id: 7 },
];

const ageGroupSelectList = [
  { value: "18-21 Years", label: "18-21 Years", id: 1 },
  { value: "22-25 Years", label: "22-25 Years", id: 2 },
  { value: "26-29 Years", label: "26-29 Years", id: 3 },
  { value: "30-33 Years", label: "30-33 Years", id: 4 },
  { value: "34-40 Years", label: "34-40 Years", id: 5 },
  { value: "40+ Years", label: "40+ Years", id: 6 },
  { value: "30+  Unmarried", label: "30+  Unmarried", id: 7 },
];
const forGraduate = [
  { value: "Aalim / Aalima", label: "Aalim / Aalima", id: 1 },
  { value: "Below 10th", label: "Below 10th", id: 2 },
  { value: "Doctor", label: "Doctor", id: 3 },
  { value: "Diploma", label: "Diploma", id: 4 },
  { value: "Engineer", label: "Engineer", id: 5 },
  { value: "Graduate", label: "Graduate", id: 6 },
  { value: "Hafiz / Hafiza", label: "Hafiz / Hafiza", id: 7 },
  { value: "Mufti", label: "Mufti", id: 8 },
  { value: "Post Graduate", label: "Post Graduate", id: 9 },
  { value: "Ph.D", label: "Ph.D", id: 10 },
  { value: "10th Pass", label: "10th Pass", id: 11 },
  { value: "12th Pass", label: "12th Pass", id: 12 },
];

const forPhysicalStatus = [
  { value: "Normal", label: "Normal" },
  { value: "Handicap", label: "Handicap" },
];

const maslakSlectBar = [
  { value: "Ahle Hadis (Salafi)", label: "Ahle Hadis (Salafi)", id: 1 },
  { value: "Barelvi (Dargah/Niyaz)", label: "Barelvi (Dargah/Niyaz)", id: 2 },
  { value: "Bohra", label: "Bohra", id: 3 },
  { value: "Deobandi (Tablighi)", label: "Deobandi (Tablighi)", id: 4 },
  { value: "Jamat Islami", label: "Jamat Islami", id: 5 },
  { value: "No Maslak (Sunni)", label: "No Maslak (Sunni)", id: 6 },
  { value: "Reverted(New) Muslim", label: "Reverted(New) Muslim", id: 7 },
  { value: "Shafai", label: "Shafai", id: 8 },
  { value: "Shia", label: "Shia", id: 9 },
];

const biradariSlectBar = [
  { value: "Momin", label: "Momin", id: 1 },
  { value: "Ansari", label: "Ansari", id: 2 },
  { value: "Attar", label: "Attar", id: 3 },
  { value: "Bade Qureshi (Qasab)", label: "Bade Qureshi (Qasab)", id: 4 },
  { value: "Bagwan", label: "Bagwan", id: 5 },
  { value: "Baid/Lodhi", label: "Baid/Lodhi", id: 6 },
  { value: "Chote Qureshi (Qasab)", label: "Chote Qureshi (Qasab)", id: 7 },
  { value: "Cutchi Memon", label: "Cutchi Memon", id: 8 },
  { value: "Khan/Pathan", label: "Khan/Pathan", id: 9 },
  { value: "Konkani", label: "Konkani", id: 10 },
  { value: "Memon", label: "Memon", id: 11 },
  { value: "Mulani", label: "Mulani", id: 12 },
  { value: "Nadaf", label: "Nadaf", id: 13 },
  { value: "No Biradari", label: "No Biradari", id: 14 },
  { value: "Pinjari", label: "Pinjari", id: 15 },
  { value: "Qureshi", label: "Qureshi", id: 16 },
  { value: "Rangrez", label: "Rangrez", id: 17 },
  { value: "Rayeen", label: "Rayeen", id: 18 },
  { value: "Sayyed", label: "Sayyed", id: 19 },
  { value: "Shaikh", label: "Shaikh", id: 20 },
  { value: "Tamboli", label: "Tamboli", id: 21 },
  { value: "Maniyar", label: "Maniyar", id: 22 },
];

const states = [
  { value: "Arunachal Pradesh", label: "Arunachal Pradesh", id: 1 },
  { value: "Assam", label: "Assam", id: 2 },
  { value: "Bihar", label: "Bihar", id: 3 },
  { value: "Chandigarh", label: "Chandigarh", id: 4 },
  { value: "Chhattisgarh", label: "Chhattisgarh", id: 5 },
  { value: "Dadra and Nagar Haveli", label: "Dadra and Nagar Haveli", id: 6 },
  { value: "Daman and Diu ", label: "Daman and Diu ", id: 7 },
  { value: "Delhi", label: "Delhi", id: 8 },
  { value: "Goa", label: "Goa", id: 9 },
  { value: "Gujarat", label: "Gujarat", id: 10 },
  { value: "Haryana", label: "Haryana", id: 11 },
  { value: "Himachal Pradesh", label: "Himachal Pradesh", id: 12 },
  { value: "Jammu and Kashmir", label: "Jammu and Kashmir", id: 13 },
  { value: "Jharkhand", label: "Jharkhand", id: 14 },
  { value: "Karnataka", label: "Karnataka", id: 15 },
  { value: "Kerala", label: "Kerala", id: 16 },
  { value: "Lakshadweep", label: "Lakshadweep", id: 17 },
  { value: "Madhya Pradesh", label: "Madhya Pradesh", id: 18 },
  { value: "Maharashtra", label: "Maharashtra", id: 19 },
  { value: "Manipur", label: "Manipur", id: 20 },
  { value: "Meghalaya", label: "Meghalaya", id: 21 },
  { value: "Mizoram", label: "Mizoram", id: 22 },
  { value: "Nagaland", label: "Nagaland", id: 23 },
  { value: "Odisha", label: "Odisha", id: 24 },
  { value: "Puducherry", label: "Puducherry", id: 25 },
  { value: "Punjab", label: "Punjab", id: 26 },
  { value: "Rajasthan", label: "Rajasthan", id: 27 },
  { value: "Sikkim", label: "Sikkim", id: 28 },
  { value: "Tamil Nadu", label: "Tamil Nadu", id: 29 },
  { value: "Telangana", label: "Telangana", id: 30 },
  { value: "Tripura", label: "Tripura", id: 31 },
  { value: "Uttarakhand", label: "Uttarakhand", id: 32 },
  { value: "Uttar Pradesh", label: "Uttar Pradesh", id: 33 },
  { value: "West Bengal", label: "West Bengal", id: 34 },
];

const countries = [
  { value: "India" },
  { value: "Saudi Arabia" },
  { value: "Qatar" },
  { value: "Kuwait" },
  { value: "Bahrain" },
  { value: "USA" },
  { value: "Canada" },
  { value: "UK" },
  { value: "Oman" },
  { value: "Italy" },
  { value: "UAE" },
  { value: "Germany" },
  { value: "France" },
  { value: "South Africa" },
  { value: "Singapore" },
  { value: "Australia" },
  { value: "Malaysia" },
  { value: "Malawi" },
  { value: "Spain" },
  { value: "Algeria" },
  { value: "Ethiopia" },
  { value: "Tanzania" },
];

export {
  states,
  biradariSlectBar,
  maslakSlectBar,
  forGraduate,
  forMaritalStatus,
  forPhysicalStatus,
  selectGenderList,
  ageGroupSelectList,
  countries,
};
